### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
This one works but the tray icon is not shown, and it is shown with the current stable version

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
Ah, I see the icon now, but it's black on black for me so it's likely missing a white variant.

**Comment by travier** [comment]
> > Ah, I see the icon now, but it's black on black for me so it's likely missing a white variant.
> 
> Try quitting and re-opening KTeaTime

Does not work for me. Still black on black.

**Comment by travier** [comment]
I have the same error for sound. Maybe it needs a sound theme.

**Comment by travier** [comment]
Hum,  I don't follow

**Comment by travier** [comment]
```
{
    "errors": [
        "non-svg-icon-in-scalable-folder"
    ],
    "warnings": [
        "appstream-screenshot-missing-caption"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by Justinzobel** [comment]
Build expired.

bot, build

**Comment by Justinzobel** [comment]
I get the tray icon but no sound or popup for when the timer goes off.

Maybe we need to add a dependency, I see `kf.notifications: Failed to play sound with canberra: File or data not found` in the terminal when run from terminal.

As for the notification it might need `--talk-name=org.kde.kconfig.notify`

**Comment by Justinzobel** [comment]
Still no notification.

Confirmed from my distro package that there is a sound and popup.

**Comment by Justinzobel** [comment]
I'm not sure why the popup doesn't happen, I think we need to build [ocean-sound-theme ](https://invent.kde.org/plasma/ocean-sound-theme) which has `ocean-sound-theme/ocean/stereo/dialog-information.oga` in it and that's the sound that plays when it's done on my repo-installed kteatime.

**Comment by Justinzobel** [comment]
Though at the same time it should just be asking the system to play that through the notification. So let's focus on that.

**Comment by Justinzobel** [comment]
Ah OK so the popups for some reason are disabled by default, so they can be enabled. However the sound is the other issue.

**Comment by Justinzobel** [comment]
I've pushed this update that fixes sound but it needs work. It builds the ocean sound theme and that will increase the size of the flatpak a bit.

We *could* just push it in depending on how big it is. But I want to see the size after the build.

However, it only needs two sounds, `dialog-information` and `dialog-error-serious`.

So maybe someone with some manifest fu can do a cleanup (or install) that only keeps those two files.

**Comment by Justinzobel** [comment]
The download is only 2.7MB. I'm merging this. If anyone wants to clean up the sounds later that's another job. The entire ocean-sound-theme installed takes up 1.2MB. :)

**Comment by travier** [comment]
Thanks Justin for fixing this!

**Pull request merged**
